### ISSUE TITLE
Can't find list contents of hymenopteramine and bovinemine

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#24]
when I view the list of lists for hymenopteramine and bovinemine, clicking on a list doesn't result in anything happening. It seems to work ok for all the other mines I've tried. 

May be related to the fact that they're running older InterMine versions? There were some minor API additions after 1.6.6 http://mineversions.apps.intermine.org/ - I may be able to help with error messages if you're getting any.

**Comment by nadia-dev** [comment]
@yochannah, bovinemine and hymenopteramine mine return "18" when I request the version on itermine software by calling "/version/intermine" endpoint. The logic relies on the fact that that the call to this endpoint will return a string of type "x.x.x" (for example, "1.7.0"). 
Will it be correct to change the logic so that first we query both "/version/intermine" and "/version/release" and if at least one of them changed, we need to reload the model?

**Comment by yochannah** [comment]
That would be one way. Alternatively, any InterMine which returns an int rather than string version is going to be an old InterMine. I don't think I'd expect their model to change unless they upgraded their InterMine to something greater than 1.6.6 *anyway*, so it might also be ok to say that if the type has changed from int to string, the model may have changed too.

**Comment by yochannah** [comment]
@deepakunni3, would I be correct in my assertion above that if BovineMine's model changed it would probably be accompanied by an InterMine upgrade too?

**Comment by deepakunni3** [comment]
@yochannah We are upgrading both BovineMine and HymenopteraMine to InterMine 1.7.3. 

Due to certain constraints we had to take down the previous instances that we had available for BlueGenes.

But I'll be sure to update this issue once its ready :)

**Comment by nadia-dev** [comment]
I left only release check for now.
