### ISSUE TITLE
search results: don't seem to be updating after the first search

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#5]
I don't think the search updates after the first search (for example, I searched ADH and then FKH (both fly gene symbols), but right now i think it still shows ADH results, not FKH. I think it may be appending results to the end of the list repeatedly as well?

Similarly I'm not sure the filters are working.

**Comment by nadia-dev** [comment]
I fixed reloading of the search results and after refine search. The question I have is the following: should refine search tab reload after we first refined search? For example, I am searching for "ADH" -> see the result -> go to refine search page -> select mine and category to refine by -> go back to search page -> view refined result -> go to refine page and I can see all mines and categories from the very first search (before refine). Is it how we want it?
To me it makes sense because this way we don't have to perform the search again if we need to refine it by other mine and/or category.

**Comment by yochannah** [comment]
Makes sense to me!
